-- ============================================================================
-- Migration 005: superseded no-op
-- ============================================================================
-- Originally forced chunks_vectors back to vector(768)/nomic-embed-text to
-- correct a then-broken 004 that had it stuck at vector(4096). 004 is now
-- the authoritative schema and already declares the correct dimension for
-- the configured embedding model (see config.yaml's embedding.dimensions
-- and migrations/004_app_schema.sql). Re-applying this migration's original
-- body on every fresh provision was silently reverting every new project's
-- chunks_vectors column back to vector(768), which then rejected every
-- 4096-dim vector insert from qwen3-embedding:8b.
--
-- Kept as a no-op (rather than deleted) so scripts/migrate.py's
-- corpus.schema_migrations bookkeeping stays stable for databases that
-- already recorded this filename as applied, and so the migration
-- numbering doesn't shift under any tooling that references it by name.
SELECT 1;
